#include <stm32l1xx.h>

void GPIO_Init()
	{
		//GPIOA CONFIGURATION FOR USART1 //pa9- USART1_TX, pa10- USART1_RX
		RCC -> AHBENR |= RCC_AHBENR_GPIOAEN;	
		GPIOA -> MODER |= (GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1);//AF for PA9 and PA10
		GPIOA -> OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR9_1 | GPIO_OSPEEDER_OSPEEDR10_1);
		GPIOA -> OTYPER &= ~(GPIO_OTYPER_OT_9);//push-pull for output
		GPIOA -> PUPDR &= ~(GPIO_PUPDR_PUPDR10);//no pull-up, ?pull-down? for input
		GPIOA -> AFR[1] |= (0x770);
		
		//GPIOA CONFIGURATION FOR USART1 //PB10- USART1_TX, PB11- USART1_RX
		RCC -> AHBENR |= RCC_AHBENR_GPIOBEN;	
		GPIOB -> MODER |= (GPIO_MODER_MODER10_1 | GPIO_MODER_MODER11_1);
		GPIOB -> OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR10 | GPIO_OSPEEDER_OSPEEDR11);
		GPIOB -> OTYPER &= ~(GPIO_OTYPER_OT_10);//push-pull for output
		GPIOB -> PUPDR &= ~(GPIO_PUPDR_PUPDR11);//no pull-up, ?pull-down? for input
		GPIOB -> AFR[1] |= (0x7700);
	}
